/* This file was generated by SableCC (http://www.sablecc.org/). */

package cpparser.node;

import cpparser.analysis.*;

@SuppressWarnings("nls")
public final class AE4mode5E4 extends PE4
{
    private PE4 _e4_;
    private TMod _mod_;
    private PE5 _e5_;

    public AE4mode5E4()
    {
        // Constructor
    }

    public AE4mode5E4(
        @SuppressWarnings("hiding") PE4 _e4_,
        @SuppressWarnings("hiding") TMod _mod_,
        @SuppressWarnings("hiding") PE5 _e5_)
    {
        // Constructor
        setE4(_e4_);

        setMod(_mod_);

        setE5(_e5_);

    }

    @Override
    public Object clone()
    {
        return new AE4mode5E4(
            cloneNode(this._e4_),
            cloneNode(this._mod_),
            cloneNode(this._e5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAE4mode5E4(this);
    }

    public PE4 getE4()
    {
        return this._e4_;
    }

    public void setE4(PE4 node)
    {
        if(this._e4_ != null)
        {
            this._e4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e4_ = node;
    }

    public TMod getMod()
    {
        return this._mod_;
    }

    public void setMod(TMod node)
    {
        if(this._mod_ != null)
        {
            this._mod_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mod_ = node;
    }

    public PE5 getE5()
    {
        return this._e5_;
    }

    public void setE5(PE5 node)
    {
        if(this._e5_ != null)
        {
            this._e5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._e4_)
            + toString(this._mod_)
            + toString(this._e5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._e4_ == child)
        {
            this._e4_ = null;
            return;
        }

        if(this._mod_ == child)
        {
            this._mod_ = null;
            return;
        }

        if(this._e5_ == child)
        {
            this._e5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._e4_ == oldChild)
        {
            setE4((PE4) newChild);
            return;
        }

        if(this._mod_ == oldChild)
        {
            setMod((TMod) newChild);
            return;
        }

        if(this._e5_ == oldChild)
        {
            setE5((PE5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
