/* This file was generated by SableCC (http://www.sablecc.org/). */

package cpparser.node;

import cpparser.analysis.*;

@SuppressWarnings("nls")
public final class AMethodArgumentsMethodDecl extends PMethodDecl
{
    private PMethodHdr _methodHdr_;
    private TLeftBrace _leftBrace_;
    private PFormals _formals_;
    private TRightBrace _rightBrace_;
    private PBlock _block_;

    public AMethodArgumentsMethodDecl()
    {
        // Constructor
    }

    public AMethodArgumentsMethodDecl(
        @SuppressWarnings("hiding") PMethodHdr _methodHdr_,
        @SuppressWarnings("hiding") TLeftBrace _leftBrace_,
        @SuppressWarnings("hiding") PFormals _formals_,
        @SuppressWarnings("hiding") TRightBrace _rightBrace_,
        @SuppressWarnings("hiding") PBlock _block_)
    {
        // Constructor
        setMethodHdr(_methodHdr_);

        setLeftBrace(_leftBrace_);

        setFormals(_formals_);

        setRightBrace(_rightBrace_);

        setBlock(_block_);

    }

    @Override
    public Object clone()
    {
        return new AMethodArgumentsMethodDecl(
            cloneNode(this._methodHdr_),
            cloneNode(this._leftBrace_),
            cloneNode(this._formals_),
            cloneNode(this._rightBrace_),
            cloneNode(this._block_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodArgumentsMethodDecl(this);
    }

    public PMethodHdr getMethodHdr()
    {
        return this._methodHdr_;
    }

    public void setMethodHdr(PMethodHdr node)
    {
        if(this._methodHdr_ != null)
        {
            this._methodHdr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._methodHdr_ = node;
    }

    public TLeftBrace getLeftBrace()
    {
        return this._leftBrace_;
    }

    public void setLeftBrace(TLeftBrace node)
    {
        if(this._leftBrace_ != null)
        {
            this._leftBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftBrace_ = node;
    }

    public PFormals getFormals()
    {
        return this._formals_;
    }

    public void setFormals(PFormals node)
    {
        if(this._formals_ != null)
        {
            this._formals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formals_ = node;
    }

    public TRightBrace getRightBrace()
    {
        return this._rightBrace_;
    }

    public void setRightBrace(TRightBrace node)
    {
        if(this._rightBrace_ != null)
        {
            this._rightBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightBrace_ = node;
    }

    public PBlock getBlock()
    {
        return this._block_;
    }

    public void setBlock(PBlock node)
    {
        if(this._block_ != null)
        {
            this._block_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._block_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._methodHdr_)
            + toString(this._leftBrace_)
            + toString(this._formals_)
            + toString(this._rightBrace_)
            + toString(this._block_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._methodHdr_ == child)
        {
            this._methodHdr_ = null;
            return;
        }

        if(this._leftBrace_ == child)
        {
            this._leftBrace_ = null;
            return;
        }

        if(this._formals_ == child)
        {
            this._formals_ = null;
            return;
        }

        if(this._rightBrace_ == child)
        {
            this._rightBrace_ = null;
            return;
        }

        if(this._block_ == child)
        {
            this._block_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._methodHdr_ == oldChild)
        {
            setMethodHdr((PMethodHdr) newChild);
            return;
        }

        if(this._leftBrace_ == oldChild)
        {
            setLeftBrace((TLeftBrace) newChild);
            return;
        }

        if(this._formals_ == oldChild)
        {
            setFormals((PFormals) newChild);
            return;
        }

        if(this._rightBrace_ == oldChild)
        {
            setRightBrace((TRightBrace) newChild);
            return;
        }

        if(this._block_ == oldChild)
        {
            setBlock((PBlock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
