/* This file was generated by SableCC (http://www.sablecc.org/). */

package cpparser.node;

import cpparser.analysis.*;

@SuppressWarnings("nls")
public final class AType3Field extends PField
{
    private PType _type_;
    private TIdentifier _three_;
    private TLeftSbrace _leftSbrace_;
    private TIntegerLiteral _integerLiteral_;
    private TRightSbrace _rightSbrace_;
    private TSemicolon _semicolon_;

    public AType3Field()
    {
        // Constructor
    }

    public AType3Field(
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") TIdentifier _three_,
        @SuppressWarnings("hiding") TLeftSbrace _leftSbrace_,
        @SuppressWarnings("hiding") TIntegerLiteral _integerLiteral_,
        @SuppressWarnings("hiding") TRightSbrace _rightSbrace_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setType(_type_);

        setThree(_three_);

        setLeftSbrace(_leftSbrace_);

        setIntegerLiteral(_integerLiteral_);

        setRightSbrace(_rightSbrace_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AType3Field(
            cloneNode(this._type_),
            cloneNode(this._three_),
            cloneNode(this._leftSbrace_),
            cloneNode(this._integerLiteral_),
            cloneNode(this._rightSbrace_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAType3Field(this);
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public TIdentifier getThree()
    {
        return this._three_;
    }

    public void setThree(TIdentifier node)
    {
        if(this._three_ != null)
        {
            this._three_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._three_ = node;
    }

    public TLeftSbrace getLeftSbrace()
    {
        return this._leftSbrace_;
    }

    public void setLeftSbrace(TLeftSbrace node)
    {
        if(this._leftSbrace_ != null)
        {
            this._leftSbrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leftSbrace_ = node;
    }

    public TIntegerLiteral getIntegerLiteral()
    {
        return this._integerLiteral_;
    }

    public void setIntegerLiteral(TIntegerLiteral node)
    {
        if(this._integerLiteral_ != null)
        {
            this._integerLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._integerLiteral_ = node;
    }

    public TRightSbrace getRightSbrace()
    {
        return this._rightSbrace_;
    }

    public void setRightSbrace(TRightSbrace node)
    {
        if(this._rightSbrace_ != null)
        {
            this._rightSbrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightSbrace_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._type_)
            + toString(this._three_)
            + toString(this._leftSbrace_)
            + toString(this._integerLiteral_)
            + toString(this._rightSbrace_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._three_ == child)
        {
            this._three_ = null;
            return;
        }

        if(this._leftSbrace_ == child)
        {
            this._leftSbrace_ = null;
            return;
        }

        if(this._integerLiteral_ == child)
        {
            this._integerLiteral_ = null;
            return;
        }

        if(this._rightSbrace_ == child)
        {
            this._rightSbrace_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._three_ == oldChild)
        {
            setThree((TIdentifier) newChild);
            return;
        }

        if(this._leftSbrace_ == oldChild)
        {
            setLeftSbrace((TLeftSbrace) newChild);
            return;
        }

        if(this._integerLiteral_ == oldChild)
        {
            setIntegerLiteral((TIntegerLiteral) newChild);
            return;
        }

        if(this._rightSbrace_ == oldChild)
        {
            setRightSbrace((TRightSbrace) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
