/* This file was generated by SableCC (http://www.sablecc.org/). */

package cpparser.node;

import cpparser.analysis.*;

@SuppressWarnings("nls")
public final class AE3onlyE2 extends PE2
{
    private PE3 _left_;

    public AE3onlyE2()
    {
        // Constructor
    }

    public AE3onlyE2(
        @SuppressWarnings("hiding") PE3 _left_)
    {
        // Constructor
        setLeft(_left_);

    }

    @Override
    public Object clone()
    {
        return new AE3onlyE2(
            cloneNode(this._left_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAE3onlyE2(this);
    }

    public PE3 getLeft()
    {
        return this._left_;
    }

    public void setLeft(PE3 node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PE3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
