/* This file was generated by SableCC (http://www.sablecc.org/). */

package cpparser.node;

import cpparser.analysis.*;

@SuppressWarnings("nls")
public final class AE5complementE5 extends PE5
{
    private TComplement _complement_;
    private PE5 _e5_;

    public AE5complementE5()
    {
        // Constructor
    }

    public AE5complementE5(
        @SuppressWarnings("hiding") TComplement _complement_,
        @SuppressWarnings("hiding") PE5 _e5_)
    {
        // Constructor
        setComplement(_complement_);

        setE5(_e5_);

    }

    @Override
    public Object clone()
    {
        return new AE5complementE5(
            cloneNode(this._complement_),
            cloneNode(this._e5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAE5complementE5(this);
    }

    public TComplement getComplement()
    {
        return this._complement_;
    }

    public void setComplement(TComplement node)
    {
        if(this._complement_ != null)
        {
            this._complement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._complement_ = node;
    }

    public PE5 getE5()
    {
        return this._e5_;
    }

    public void setE5(PE5 node)
    {
        if(this._e5_ != null)
        {
            this._e5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._complement_)
            + toString(this._e5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._complement_ == child)
        {
            this._complement_ = null;
            return;
        }

        if(this._e5_ == child)
        {
            this._e5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._complement_ == oldChild)
        {
            setComplement((TComplement) newChild);
            return;
        }

        if(this._e5_ == oldChild)
        {
            setE5((PE5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
