/* This file was generated by SableCC (http://www.sablecc.org/). */

package cpparser.node;

import cpparser.analysis.*;

@SuppressWarnings("nls")
public final class ABoolType extends PType
{
    private TBool _bool_;
    private TSemicolon _semicolon_;

    public ABoolType()
    {
        // Constructor
    }

    public ABoolType(
        @SuppressWarnings("hiding") TBool _bool_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setBool(_bool_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new ABoolType(
            cloneNode(this._bool_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolType(this);
    }

    public TBool getBool()
    {
        return this._bool_;
    }

    public void setBool(TBool node)
    {
        if(this._bool_ != null)
        {
            this._bool_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bool_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bool_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bool_ == child)
        {
            this._bool_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bool_ == oldChild)
        {
            setBool((TBool) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
