/* This file was generated by SableCC (http://www.sablecc.org/). */

package cpparser.node;

import cpparser.analysis.*;

@SuppressWarnings("nls")
public final class AClassMemberDeclsClassMemberDecls extends PClassMemberDecls
{
    private PClassMemberDecls _classMemberDecls_;
    private PClassMember _classMember_;

    public AClassMemberDeclsClassMemberDecls()
    {
        // Constructor
    }

    public AClassMemberDeclsClassMemberDecls(
        @SuppressWarnings("hiding") PClassMemberDecls _classMemberDecls_,
        @SuppressWarnings("hiding") PClassMember _classMember_)
    {
        // Constructor
        setClassMemberDecls(_classMemberDecls_);

        setClassMember(_classMember_);

    }

    @Override
    public Object clone()
    {
        return new AClassMemberDeclsClassMemberDecls(
            cloneNode(this._classMemberDecls_),
            cloneNode(this._classMember_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClassMemberDeclsClassMemberDecls(this);
    }

    public PClassMemberDecls getClassMemberDecls()
    {
        return this._classMemberDecls_;
    }

    public void setClassMemberDecls(PClassMemberDecls node)
    {
        if(this._classMemberDecls_ != null)
        {
            this._classMemberDecls_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classMemberDecls_ = node;
    }

    public PClassMember getClassMember()
    {
        return this._classMember_;
    }

    public void setClassMember(PClassMember node)
    {
        if(this._classMember_ != null)
        {
            this._classMember_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classMember_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._classMemberDecls_)
            + toString(this._classMember_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._classMemberDecls_ == child)
        {
            this._classMemberDecls_ = null;
            return;
        }

        if(this._classMember_ == child)
        {
            this._classMember_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._classMemberDecls_ == oldChild)
        {
            setClassMemberDecls((PClassMemberDecls) newChild);
            return;
        }

        if(this._classMember_ == oldChild)
        {
            setClassMember((PClassMember) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
