/* This file was generated by SableCC (http://www.sablecc.org/). */

package cpparser.node;

import cpparser.analysis.*;

@SuppressWarnings("nls")
public final class ATClassClassHdr extends PClassHdr
{
    private TKClass _kClass_;
    private TIdentifier _identifier_;

    public ATClassClassHdr()
    {
        // Constructor
    }

    public ATClassClassHdr(
        @SuppressWarnings("hiding") TKClass _kClass_,
        @SuppressWarnings("hiding") TIdentifier _identifier_)
    {
        // Constructor
        setKClass(_kClass_);

        setIdentifier(_identifier_);

    }

    @Override
    public Object clone()
    {
        return new ATClassClassHdr(
            cloneNode(this._kClass_),
            cloneNode(this._identifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATClassClassHdr(this);
    }

    public TKClass getKClass()
    {
        return this._kClass_;
    }

    public void setKClass(TKClass node)
    {
        if(this._kClass_ != null)
        {
            this._kClass_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kClass_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kClass_)
            + toString(this._identifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kClass_ == child)
        {
            this._kClass_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kClass_ == oldChild)
        {
            setKClass((TKClass) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
