/* This file was generated by SableCC (http://www.sablecc.org/). */

package cplexer.analysis;

import cplexer.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTWhiteSpace(TWhiteSpace node);
    void caseTSlcomment(TSlcomment node);
    void caseTBool(TBool node);
    void caseTBreak(TBreak node);
    void caseTChar(TChar node);
    void caseTKconst(TKconst node);
    void caseTContinue(TContinue node);
    void caseTDo(TDo node);
    void caseTElse(TElse node);
    void caseTFalse(TFalse node);
    void caseTFloat(TFloat node);
    void caseTIf(TIf node);
    void caseTInt(TInt node);
    void caseTKClass(TKClass node);
    void caseTNew(TNew node);
    void caseTNull(TNull node);
    void caseTPrivate(TPrivate node);
    void caseTProtected(TProtected node);
    void caseTPublic(TPublic node);
    void caseTReturn(TReturn node);
    void caseTStatic(TStatic node);
    void caseTString(TString node);
    void caseTStruct(TStruct node);
    void caseTThis(TThis node);
    void caseTTrue(TTrue node);
    void caseTWhile(TWhile node);
    void caseTVoid(TVoid node);
    void caseTIdentifier(TIdentifier node);
    void caseTLeftBrace(TLeftBrace node);
    void caseTRightBrace(TRightBrace node);
    void caseTStar(TStar node);
    void caseTKsemicolon(TKsemicolon node);
    void caseTInteger(TInteger node);
    void caseTStringLiteral(TStringLiteral node);
    void caseEOF(EOF node);
}
